name: Master Workflow

on:
  push:
    branches:
      - 'main'

jobs:
  main:
    name: Master Workflow Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the kafka-streams-course-parent
        uses: actions/checkout@v1

      - name: Maven settings configuration
        env:
          SECRET_GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
        run: envsubst < settings.template.xml > settings.xml

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Compile the maven project
        run: ./mvnw -B compile

      - name: Deploy the maven pom archive
        run: ./mvnw -B -s settings.xml deploy
